### ISSUE TITLE
Module not display to be enabled

### ISSUE THREAD

**Issue by nsgadmin** [omarbg/dolibarr_bg#1]
Hello,
I downloaded your custom app but after completing the install, the module "appel offre" doesn't appear in the module configuration.
I cannot enable it and it doesn't work for me.
Could you advise please.
Thank you for your help
regards

**Comment by omarbg** [comment]
Hello,
i'm  still working on it  :)
to activate it please set MAIN_FEATURES_LEVEL to 2 to be visible in extremental module and next you can enable/disable it
regards

**Comment by omarbg** [comment]
see preview response
